version: '3.8'

services:
  postgres:
    image: docker.io/library/postgres:16-alpine
    container_name: wikitack-postgres
    environment:
      POSTGRES_USER: wikitack
      POSTGRES_PASSWORD: wikitack_dev_password
      POSTGRES_DB: wikitack
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wikitack"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wikitack-backend
    environment:
      DATABASE_URL: postgresql://wikitack:wikitack_dev_password@postgres:5432/wikitack
      ENVIRONMENT: development
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      postgres:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  pgadmin:
    image: docker.io/dpage/pgadmin4:latest
    container_name: wikitack-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: wikitack-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  postgres_data:
  pgadmin_data:
