version: '3.8'

services:
  postgres:
    image: docker.io/library/postgres:16-alpine
    container_name: wikitack-postgres
    environment:
      POSTGRES_USER: wikitack
      POSTGRES_PASSWORD: wikitack_dev_password
      POSTGRES_DB: wikitack
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wikitack"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: docker.io/dpage/pgadmin4:latest
    container_name: wikitack-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:
