"""Add workspaces and workspace members

Revision ID: 79d79b3aa603
Revises: 9b2d3e4e8f3c
Create Date: 2025-11-20 11:18:45.848463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79d79b3aa603'
down_revision = '9b2d3e4e8f3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Create workspaces table
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_id'), 'workspaces', ['id'], unique=False)
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=True)

    # Create workspace_members table
    op.create_table('workspace_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uix_workspace_user')
    )
    op.create_index(op.f('ix_workspace_members_id'), 'workspace_members', ['id'], unique=False)

    # Add workspace_id column as nullable first
    op.add_column('spaces', sa.Column('workspace_id', sa.Integer(), nullable=True))

    # Migrate existing spaces: Create a default workspace for each space owner
    # This SQL will:
    # 1. Create a workspace for each unique space owner
    # 2. Add owner as a member with 'owner' role
    # 3. Update spaces to belong to their owner's workspace
    connection = op.get_bind()

    # Create default workspaces for each space owner
    connection.execute(sa.text("""
        INSERT INTO workspaces (name, slug, description, owner_id, created_at, updated_at)
        SELECT
            COALESCE(u.display_name, u.username) || '''s Workspace',
            u.username || '-workspace',
            'Default workspace',
            u.id,
            now(),
            now()
        FROM users u
        WHERE u.id IN (SELECT DISTINCT owner_id FROM spaces)
        ON CONFLICT DO NOTHING
    """))

    # Add workspace owners as members
    connection.execute(sa.text("""
        INSERT INTO workspace_members (workspace_id, user_id, role, created_at, updated_at)
        SELECT w.id, w.owner_id, 'owner', now(), now()
        FROM workspaces w
        ON CONFLICT DO NOTHING
    """))

    # Update existing spaces to belong to their owner's workspace
    connection.execute(sa.text("""
        UPDATE spaces s
        SET workspace_id = w.id
        FROM workspaces w
        WHERE s.owner_id = w.owner_id
        AND s.workspace_id IS NULL
    """))

    # Now make workspace_id NOT NULL
    op.alter_column('spaces', 'workspace_id', nullable=False)

    # Drop the unique constraint on slug (now slug is unique within workspace, not globally)
    op.drop_constraint(op.f('spaces_slug_key'), 'spaces', type_='unique')

    # Create foreign key
    op.create_foreign_key(None, 'spaces', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'spaces', type_='foreignkey')
    op.create_unique_constraint(op.f('spaces_slug_key'), 'spaces', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_column('spaces', 'workspace_id')
    op.drop_index(op.f('ix_workspace_members_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_id'), table_name='workspaces')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
